# https://github.com/DoozyX/clang-format-lint-action
name: indentation

on: [push, pull_request]

concurrency:
  group: ${{ github.event_name }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.13
      with:
        source: '.'
        exclude: './doc/doxygen/headers'
        extensions: 'h.in,h,cc,cpp'
        clangFormatVersion: 11
        inplace: true
    - run: |
        git diff
        git diff-files --quiet || exit $?
